trigger:
- main

pool: 
  name: 'Default'

steps:
- task: Maven@4
  inputs:
    azureSubscription: 'Free Trial(5)(5571e1cd-c152-4666-889b-580c92bd1832)'
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'Path'
    jdkDirectory: '/usr/lib/jvm/java-17-openjdk-amd64'
    mavenVersionOption: 'Path'
    mavenDirectory: '/home/scanuser/maven/apache-maven-3.9.9'
    mavenSetM2Home: true
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    spotBugsRunAnalysis: true

- script: |
    mkdir -p $(Pipeline.Workspace)/target/spotbugs
    cp target/spotbugs/spotbugsXml.xml $(Pipeline.Workspace)/target/spotbugs/
  displayName: 'Copy SpotBugs Report'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/target/spotbugs'
    artifact: 'SpotBugsReports'
    publishLocation: 'pipeline'
