trigger:
- main

pool: 
  name: default
  demands: agent.name
  vmImage: 'ubuntu-latest'

stages: 
- stage:
  jobs:
  - job:
    steps:
    - task: Maven@4
      inputs:
        azureSubscription: 'Free Trial(5571e1cd-c152-4666-889b-580c92bd1832)'
        mavenPomFile: 'pom.xml'
        goals: 'clean verify'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
        spotBugsRunAnalysis: true

