trigger:
- main

pool: 
  name: default
  demands: agent.name
  vmImage: 'ubuntu-latest'  

stages:
- stage: 
  jobs:
  - job: 
    steps:
    - task: Maven@4
      inputs:
        azureSubscription: 'Free Trial(2)(5571e1cd-c152-4666-889b-580c92bd1832)'
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'Path'
        jdkDirectory: '/root/java17/jdk-17.0.11'
        mavenVersionOption: 'Path'
        mavenDirectory: '/root/maven/apache-maven-3.9.9'
        mavenSetM2Home: false
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
