trigger:
- main

pool: 
  name: 'Default'

stages:
- stage: BuildAndTest
  jobs:
  - job: MavenBuild
    pool: 
      name: 'Default'
      demands: 
        - agent.name -equals ScanVM
    steps:
    - script: |
        export JAVA_HOME=/root/java17/jdk-17.0.11
        export PATH=$JAVA_HOME/bin:$PATH
        export M2_HOME=/root/maven/apache-maven-3.9.9
        export PATH=$M2_HOME/bin:$PATH
        
        # Run Maven commands
        mvn clean install
      displayName: 'Run Maven Build and Test'
